### ISSUE TITLE
Add support for Python 3 when handling bytes

### ISSUE THREAD

**Issue by jsabater** [szepeviktor/debian-server-tools#13]
Hi, Viktor!

Just tried to use your tool to convert a private_key.json from the latest version of Certbot to PEM format using Python 3.9 under Debian 11 Bullseye and found this error:

```
Traceback (most recent call last):
  File "/home/ansible/bin/jwk_convert.py", line 31, in <module>
    PKEY[k] = enc(v.encode())
  File "/home/ansible/bin/jwk_convert.py", line 26, in enc
    return '0x'+binascii.hexlify(base64.b64decode(data, b'-_')).upper()
TypeError: can only concatenate str (not "bytes") to str
```

I had converted the script to Python 3 using `2to3` but handling strings of bytes seems to need specific knowledge, which I don't have. I think the problem is here:

```
data += b'=' * missing_padding
```

I've tried to research this topic without success. Would you feel like upgrading the script to Python 3? I think that the need to convert JWK to PEM is going to be there for a while for all us Ansible users.

Incidentally, I'd love to create an Ansible Playbook to do the whole process, maybe through a module.

Thanks in advance and happy new year.

**Comment by szepeviktor** [comment]
Please continue in https://github.com/candango/automatoes/discussions/114
I don't speak Python.
Sorry.

**Comment by piraz** [comment]
Ok, this is not part of automatoes. Do you want that I come with a pull request here @szepeviktor?

**Comment by szepeviktor** [comment]
@piraz That would be beautiful :)

**Comment by piraz** [comment]
Can you open this ticket please?

**Comment by piraz** [comment]
Just let me know if you have any problems.

**Comment by szepeviktor** [comment]
@jsabater Could you test it once more please?

**Comment by jsabater** [comment]
I can confirm that it is working now. I went through the whole process and was able to generate my `production.key` file from Certbot's `private_key.json` file. This production.key file in PEM format is exactly the same I had previously generated using both:

1. The previous version of `jwk_convert.py` using Python 2.7 (on my laptop).
2. The private key generated using this [JWK-to-PEM converter](https://8gwifi.org/jwkconvertfunctions.jsp).

As further improvement, may I suggest using an env-based shebang?

```#!/usr/bin/env python```

Cheers!

**Comment by jsabater** [comment]
Yes, especially when in a virtual environment, where you wouldn't be using `/usr/bin/python`.

**Comment by piraz** [comment]
By the way guys ... I did it. Don't need to convert to ans1 and use openssl anymore. Just got the prime numbers from the the certbot account and generated the PEM file using cryptography.

What would be a better way to use? Maybe:

`manuale migrate <path_where_private_key.json_and_other_files_are_located> <path_where_you_want_account.json_to_be_generated>`

Now I'm packing up and creating a command to execute every step in just one command only.

Working on that here: https://github.com/candango/automatoes/issues/116

I'll prepare a release for that.

**Comment by jsabater** [comment]
Very nice work. Would it be possible to have that functionality also in a simple script such as `jwk_convert.py`? I ask because it's often a one-time thing and would be easy to add to an Ansible playbook:

1. Download the script from a remote URL.
2. Run the command and obtain the desired state.
3. Keep executing tasks to e.g. issue a Let's Encrypt certificate for your web server.

Keep up the good work!

**Comment by szepeviktor** [comment]
Someone used certbot and I've migrated that server to use manuale.
Then archived `jwk_convert.py` in this repo.
That is all I have.

**Comment by szepeviktor** [comment]
certbot is a Danger 👹 
don't talk to people using certbot 🙃

**Comment by piraz** [comment]
@szepeviktor It is done! Whatever you are doing with this script can be replaced by:

`manuale migrate -c <path_to_the_certbot_account_directory>`

The path_to_certbot_account_directory is the path that has the files private_key.json and regr.json.

The command will convert the key from private_key.json and uri on regr.json, and generate the account.json file in the current directory.

**Comment by szepeviktor** [comment]
Thank you Flavio!

**Comment by jsabater** [comment]
Thank you very much for your work, Flavio!
