### ISSUE TITLE
How to run the resize before Ubuntu server 22 LTS boot

### ISSUE THREAD

**Issue by mickeyjohn** [szepeviktor/debian-server-tools#24]
Hi,

Thanks for sharing those useful scripts. I am trying  to resize an VM server with a LV mounted root with no free space at the end.

Would anyone please share how to run this script before before Ubuntu server 22 boot up?

Script file: [debian-setup/debian-resizefs.sh](https://github.com/szepeviktor/debian-server-tools/blob/master/debian-setup/debian-resizefs.sh)

I tried putting it in the /etc/init.d/ folder but It seems does not work. Thank you very much in advance.

Regards.

**Comment by szepeviktor** [comment]
> how to run this script

Hello!

This script does that for you. This is not the resizer script. This script installs the resizer script into initramfs.
I see you cannot boot up your system to run this script.
Then you need a recovery CD or another running operating system.

If you read through the script, every step could be easily executed manually except `update-initramfs`.

**Comment by mickeyjohn** [comment]
@szepeviktor I am really appreciated your prompt response. However, I still does not get it completely. 

So, the script needs to be executed within a terminal first ?  then the server needed to be rebooted after that ?  and done.

Thanks.

**Comment by szepeviktor** [comment]
Yess!! ✅
