### ISSUE TITLE
Docker-izing Apache

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/debian-server-tools#3]
- [ ] Main configs, mods-available/ (SSL certificates), conf-enabled/
- [ ] Virtualhost configs (sites-enabled/)
- [ ] Filesystem access to document root with proper permissions + read-only
- [ ] Answer on TCP port 80,443
- [ ] FastCGI UDS socket/TCP port for PHP-FPM
- [ ] Permanent log storage
- [ ] etc...

**Comment by szepeviktor** [comment]
- [ ] Main configs, mods-available/ (SSL certificates), conf-enabled/
- [ ] Virtualhost configs (sites-enabled/)
- [ ] Filesystem access to document root with proper permissions + read-only
- [ ] Answer on TCP port 80,443
- [ ] FastCGI socket/TCP port for PHP-FPM
- [ ] Permanent log storage
- [ ] etc...

@peripau Come and see our list.

**Comment by szepeviktor** [comment]
- Q: Build in SSL certs into the image?

**Comment by bccjlin** [comment]
ok
